apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-task
spec:
  replicas: 3
  selector:
    matchLabels:
      app: final-task
  template:
    metadata:
      labels:
        app: final-task
        track: stable
    spec:
      containers:
        - name: final-task
          image: "gcr.io/high-office-331319/final-task:45931a9d94456e185bc9cc2332589e24764080b5"
          ports:
            - name: http  
              containerPort: 3000
            - name: health
                containerPort: 81
